### ISSUE TITLE
List - No delete button.

### ISSUE THREAD

**Issue by grubinohyp3r** [gera2ld/request-x#1]
First of all, awesome extension! very helpfull! :)

Found that you can create a new list of rules, and new tab appears (list). But there's no option to delete or rename that new tab.

Thanks!

**Comment by gera2ld** [comment]
By double clicking on the tab title, you can modify the list meta or delete it.
I think I will make it more explicit later.

**Comment by grubinohyp3r** [comment]
Cool!
Otherwise, a "Help" tab with this double click tip, can work too.

Thanks!

**Comment by gera2ld** [comment]
closed via [v1.1.0](/gera2ld/request-blocker/releases/tag/v1.1.0)

**Comment by grubinohyp3r** [comment]
Great change with the dashboard! Thanks! 
https://media.giphy.com/media/r1fDuPIcs18d2/giphy-downsized-large.gif
