### ISSUE TITLE
Need option to export all Lists.

### ISSUE THREAD

**Issue by vigneshrajarr** [gera2ld/request-x#10]
I came into this requirement when I was switching from Chrome to Brave. I need to export every list 1 by 1. Instead I need an option to export and import all the lists at once.

**Comment by gera2ld** [comment]
In v2.4.0 you can:
- select all lists in a group by clicking the first one, then <kbd>Shift</kbd>+click the last one
- copy them with <kbd>Cmd</kbd>+<kbd>C</kbd>
- then paste them with <kbd>Cmd</kbd>+<kbd>V</kbd> to the same extension in another browser

I think this way mitigates the issue even though there is no global export yet.
