### ISSUE TITLE
Rules are not fetching

### ISSUE THREAD

**Issue by Harfho** [gera2ld/request-x#11]
After updating to version 2.4.0
Subscribe Rules are not updating after clicking on fetch All
and I also try subscribing to new rule but still unable to do so.

I check the background network and can see it was able to get the rules but somehow they are not updating.

But when I downgraded to version 2.3.0 it works well , the rules update and subscribing to new rules also works

**Comment by gera2ld** [comment]
Do you have `type` defined in the remote list? You can see a valid structure by exporting an existing list.
From v2.4.0 on `type` is required and must match the existing list. I think it's better to show an error message.

**Comment by Harfho** [comment]
no, type is not defined in the remote list.

that definitely the issue.

is there any way you can identify the remote list , to automatically sent the type if it was not specify.

**Comment by Harfho** [comment]
sorry, how often do the list of subscribed list get updated automatically? or do  i have to always go to the menu to fetch new update of the list all time?

**Comment by gera2ld** [comment]
They should be fetched every 2 hours:

https://github.com/gera2ld/request-x/blob/45143f11cde3b2d79ba73e8139cba5937c78ac04/src/handler/index.ts#L177-L184

**Comment by Harfho** [comment]
> They should be fetched every 2 hours:
> 
> https://github.com/gera2ld/request-x/blob/45143f11cde3b2d79ba73e8139cba5937c78ac04/src/handler/index.ts#L177-L184


What if there is a place to manually set the intervals to fetch new update.and it would be 2h by default.
