### ISSUE TITLE
Deselected Lists are not shown

### ISSUE THREAD

**Issue by vigneshrajarr** [gera2ld/request-x#12]
Deselected Lists are not shown in the menu that appears on clicking extension icon.

**Comment by gera2ld** [comment]
Yes, this is the expected behavior since you may have a lot of lists disabled and I suppose you care more about those enabled.
This feature is used for quickly checking the lists that are applied to open pages and also providing a way to disable unwanted lists.

**Comment by vigneshrajarr** [comment]
I use about 10-15 lists only. It will be helpful if there is an option to show all lists
