### ISSUE TITLE
Pls provide option to modify parameters, if possible

### ISSUE THREAD

**Issue by vigneshrajarr** [gera2ld/request-x#14]
Why ?
Some websites I use some nocache parameter that varies between multiple sites, for JS, CSS etc. So to save data and page loading time, it will be useful.

**Comment by gera2ld** [comment]
I think parameters are already included in the URL, which can be matched and modified by RegExp. Can you provide an example?

**Comment by vigneshrajarr** [comment]
Ex:
`https://ex.com/js/admin/admin.min.js?_=1662385992826`
`https://ex.com/csss/admin/admin.min.css?nocache=166238433321`
These requests serve js, css files and it changes rarely. So, I want to remove these parameters before sending the request to cache them. It would be nice to have a clean UI instead of writing regex.
