### ISSUE TITLE
redirect to javascript:

### ISSUE THREAD

**Issue by Harfho** [gera2ld/request-x#15]
Is there anyway to make it redirect page to javascript: instead of valid page url that start with https://

**Comment by gera2ld** [comment]
It seems the validation rule need to be updated.

**Comment by Harfho** [comment]
is there still going to be an update

**Comment by gera2ld** [comment]
PR is welcome.
Or wait until I survive my tough time.

**Comment by Harfho** [comment]
I am sorry to hear that you are going through a tough time right now. It's important to remember that you are not alone.
Remember that tough times don't last forever. Take care of yourself and seek out the support you need to get through this. if i can help in anyway i would be glad to let me know

**Comment by gera2ld** [comment]
Closing since this is not allowed in manifest v3 as per [Chrome documentation](https://developer.chrome.com/docs/extensions/reference/api/declarativeNetRequest#type-Redirect).
