### ISSUE TITLE
First request is never blocked

### ISSUE THREAD

**Issue by NotizMe** [gera2ld/request-x#19]
Hi,

First of: big thank you for this wonderfull extension. It has helped me so much.

For blocking distractions I'm trying to simply block https://super-hex.io/.

But for some reason when typing `super-hex.io` in the URL bar and hitting enter, the first request to `https://super-hex.io/` still returns 200 OK and isn't blocked. Any subsequent requests do get blocked. `https://super-hex.io/mainloop.min.js` for example, gets blocked as one of the subsequent requests.

When I enter `https://super-hex.io/mainloop.min.js` in the url bar and hit enter, the first request to `https://super-hex.io/mainloop.min.js` again isn't getting blocked.

Entering `superhex.io` the first request to `https://superhex.io/` isn't blocked, gets a 301 Moved Permanently. It redirects to `https://super-hex.io/` which also isn't blocked and returns 200 OK.

As you can see in my exported block list I tried about everything I could think of.

<details>
 <summary>My exported block list, also attached to the issue: </summary>

```json
  {
  "type": "request",
  "name": "Superhex",
  "enabled": true,
  "rules": [
    {
      "enabled": true,
      "type": "block",
      "url": "*://*.super-hex.io/*",
      "target": "",
      "comment": "",
      "methods": [],
      "requestHeaders": [],
      "responseHeaders": []
    },
    {
      "enabled": true,
      "type": "block",
      "url": "*://*.super-hex.io/",
      "target": "",
      "comment": "",
      "methods": [],
      "requestHeaders": [],
      "responseHeaders": []
    },
    {
      "enabled": true,
      "type": "block",
      "url": "*://super-hex.io/*",
      "target": "",
      "comment": "",
      "methods": [],
      "requestHeaders": [],
      "responseHeaders": []
    },
    {
      "enabled": true,
      "type": "block",
      "url": "*://super-hex.io/",
      "target": "",
      "comment": "",
      "methods": [],
      "requestHeaders": [],
      "responseHeaders": []
    },
    {
      "enabled": true,
      "type": "block",
      "url": "*://*.superhex.io/*",
      "target": "",
      "comment": "",
      "methods": [],
      "requestHeaders": [],
      "responseHeaders": []
    },
    {
      "enabled": true,
      "type": "block",
      "url": "*://*.superhex.io/",
      "target": "",
      "comment": "",
      "methods": [],
      "requestHeaders": [],
      "responseHeaders": []
    },
    {
      "enabled": true,
      "type": "block",
      "url": "*://superhex.io/*",
      "target": "",
      "comment": "",
      "methods": [],
      "requestHeaders": [],
      "responseHeaders": []
    },
    {
      "enabled": true,
      "type": "block",
      "url": "*://superhex.io/",
      "target": "",
      "comment": "",
      "methods": [],
      "requestHeaders": [],
      "responseHeaders": []
    },
    {
      "enabled": true,
      "type": "block",
      "methods": [],
      "url": "/super-?hex/",
      "target": "",
      "comment": ""
    }
  ]
}
```
</details>

Attachment: [superhex.json](https://github.com/user-attachments/files/15840779/superhex.json)

[HTTP Request Blocker](https://chromewebstore.google.com/detail/http-request-blocker/eckpjmeijpoipmldfbckahppeonkoeko?hl=en) can block from the first request when using the URL pattern `*://*.super-hex.io/*`. But Request X is so much nicer to use. Maybe the source code at https://github.com/clupasq/ChromeHttpRequestBlocker can show you how that extension handles this. I currently don't have the time to dig into it.

Many thanks if you'd be willing to look into this. :pray:

**Comment by gera2ld** [comment]
Thanks for reaching out. It will be fixed in the next release.

BTW, this extension has migrated from Manifest V2 (which will be deprecated by Chrome soon) to V3, and the way it works has changed significantly. Consequently, match patterns (e.g., `*://super-hex.io/*`) are no longer supported due to technical constraints. You might need to update it to either [URL filters](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/declarativeNetRequest/RuleCondition#urlfilter) or regular expressions.

**Comment by NotizMe** [comment]
Hi,

I haven't seen any change in behavior. The issue is still there in version 3.0.2 of request-x on Google Chrome Version 131.0.6778.85 (Official Build) (64-bit).

The patterns you called "match patterns" should be valid URL filters according to the documentation I could find on URL filters. But anyway, the regex should already be enough to catch the requests I want to block.
