### ISSUE TITLE
Subscribing delay

### ISSUE THREAD

**Issue by tbyte80** [gera2ld/request-x#2]
Hello and thanks for your work!
I have a question: there is some delay between subscribing to a list and actually fetching the entries from the server. I thought at first that subscribing doesn't work at all. Maybe it would be an improvement to immediately update the list on subscribing? Also an option would be nice to specify how often a list should be synced with the server.

It also took me a few moments to find out how to export an existing list. So a general button with a list chooser would come handy.

Best regards :) !

**Comment by gera2ld** [comment]
Currently not support export for multiple lists, so I think a general button with list chooser is unnecessary.
Actually I put the buttons in a dropdown so that the user does not have to switch to the list before operating it.
