### ISSUE TITLE
hello how to redirect to https?

### ISSUE THREAD

**Issue by dhana-exe** [gera2ld/request-x#5]
Hello...
can i use this for redirect to ssl for spesific website?
like http://imgbox.com to https://imgbox.com ?

**Comment by gera2ld** [comment]
Sure, I'm using it for this feature too.
<img width="660" alt="Screen Shot 2020-09-16 at 13 34 31" src="https://user-images.githubusercontent.com/3139113/93296225-62000880-f821-11ea-9ed2-32ad785602b6.png">

If you just want to redirect exact `http://imgbox.com/` to `https://imgbox.com/`, here is what you need:
- URL: `http://imgbox.com/`
- target: `https://imgbox.com/`

If you want to redirect all URLs in this site from HTTP to HTTPS, like what is done in the screenshot above, you'll have to use RegExp to match the path names. Here is what you need:
- URL: `/^http:\/\/imgbox\.com\/(.*)$/`
- target: `https://imgbox.com/$1`

**Comment by dhana-exe** [comment]
ok thanks a lot :)
