### ISSUE TITLE
The new update doesn't work on kiwi browser 

### ISSUE THREAD

**Issue by Harfho** [gera2ld/request-x#7]
The new update doesn't work on kiwi browser version ==https://github.com/kiwibrowser/src/releases/tag/1019022375
But the last version works well on it.

**Comment by gera2ld** [comment]
Looks like the specific version of Kiwi does not support `extraHeaders` option here:

https://github.com/gera2ld/request-x/blob/a4888bcc2578ad4db478ba2613ab53e5a7e35135/src/handler/index.ts#L118

Is there any reason to stick to an old version of the browser?

**Comment by Harfho** [comment]
Yeah , the new update , seems to select extension , and mean while its most of the one I used. Well maybe you can send the old copy version to me. THANKS

**Comment by gera2ld** [comment]
Could you try this build with unsupported features ignored? If it works I will release a fix version soon.

[request-x-test.zip](https://github.com/gera2ld/request-x/files/7797490/request-x-test.zip)

**Comment by Harfho** [comment]
Yeah ,it works .
